package com.eqriesracingteam.garage.model;

public enum AppointmentStatus {
    AFSPRAAK_GEPLAND, INSPECTIE_KLAAR, AKKOORD_KLANT, NIET_UITVOEREN, REPARATIE_GEPLAND, REPARATIE_UITGEVOERD, FACTUUR_AANGEMAAKT, BETAALD
    }
